import { useState } from 'react';
import { SearchBar } from './components/SearchBar';
import { SeatList } from './components/SeatList';
import { AddSeatForm } from './components/AddSeatForm';

export interface Seat {
  id: string;
  shortId: string;
  tableNumber: string;
}

export default function App() {
  const [seats, setSeats] = useState<Seat[]>([
    { id: '1', shortId: 'ashleyy', tableNumber: '24' },
    { id: '2', shortId: 'yhdung', tableNumber: '24' },
    { id: '3', shortId: 'hwu04', tableNumber: '24' },
    { id: '4', shortId: 'lilyko', tableNumber: '24' },
    { id: '5', shortId: 'mandytsai', tableNumber: '24' },
    { id: '6', shortId: 'mei0327', tableNumber: '24' },
    { id: '7', shortId: 'michelin', tableNumber: '24' },
    { id: '8', shortId: 'ynaichia', tableNumber: '24' },
    { id: '9', shortId: 'shani', tableNumber: '24' },
    { id: '10', shortId: 'daiyupin', tableNumber: '24' },
    { id: '11', shortId: 'kellycheng', tableNumber: '24' },
    { id: '12', shortId: 'chihyi', tableNumber: '25' },
    { id: '13', shortId: 'kwu03', tableNumber: '25' },
    { id: '14', shortId: 'peggiec', tableNumber: '25' },
    { id: '15', shortId: 'seb3209', tableNumber: '25' },
    { id: '16', shortId: 'tsu01', tableNumber: '25' },
    { id: '17', shortId: 'lucienne', tableNumber: '18' },
    { id: '18', shortId: 'abbychang', tableNumber: '18' },
    { id: '19', shortId: 'khuang02', tableNumber: '18' },
    { id: '20', shortId: 'awang03', tableNumber: '18' },
    { id: '21', shortId: 'jlee09', tableNumber: '18' },
    { id: '22', shortId: 'hwang15', tableNumber: '18' },
    { id: '23', shortId: 'bonniehu', tableNumber: '18' },
    { id: '24', shortId: 'lilytseng', tableNumber: '19' },
    { id: '25', shortId: 'ychien', tableNumber: '19' },
    { id: '26', shortId: 'kshen', tableNumber: '19' },
    { id: '27', shortId: 'liminqoq', tableNumber: '19' },
    { id: '28', shortId: 'brendanc', tableNumber: '4' },
    { id: '29', shortId: 'peterpan', tableNumber: '4' },
    { id: '30', shortId: 'ychuang', tableNumber: '4' },
    { id: '31', shortId: 'yhsieh', tableNumber: '4' },
    { id: '32', shortId: 'wchiang05', tableNumber: '4' },
    { id: '33', shortId: 'awan', tableNumber: '4' },
    { id: '34', shortId: 'yihung', tableNumber: '4' },
    { id: '35', shortId: 'yliu09', tableNumber: '4' },
    { id: '36', shortId: 'chsu01', tableNumber: '4' },
    { id: '37', shortId: 'hungsheng', tableNumber: '4' },
    { id: '38', shortId: 'sonylin', tableNumber: '5' },
    { id: '39', shortId: 'stoneyu', tableNumber: '5' },
    { id: '40', shortId: 'heeroy', tableNumber: '5' },
    { id: '41', shortId: 'fandy', tableNumber: '5' },
    { id: '42', shortId: 'samfu', tableNumber: '5' },
    { id: '43', shortId: 'maxyen', tableNumber: '5' },
    { id: '44', shortId: 'pwu', tableNumber: '5' },
    { id: '45', shortId: 'lear', tableNumber: '5' },
    { id: '46', shortId: 'ytseng', tableNumber: '5' },
    { id: '47', shortId: 'ckchan', tableNumber: '5' },
    { id: '48', shortId: 'yli07', tableNumber: '11' },
    { id: '49', shortId: 'hhsu04', tableNumber: '11' },
    { id: '50', shortId: 'hwang14', tableNumber: '11' },
    { id: '51', shortId: 'itsai', tableNumber: '11' },
    { id: '52', shortId: 'jwu07', tableNumber: '11' },
    { id: '53', shortId: 'kzhang02', tableNumber: '11' },
    { id: '54', shortId: 'ronniec', tableNumber: '11' },
    { id: '55', shortId: 'jamison', tableNumber: '11' },
    { id: '56', shortId: 'askahsu', tableNumber: '11' },
    { id: '57', shortId: 'joezhang', tableNumber: '11' },
    { id: '58', shortId: 'damonkai', tableNumber: '12' },
    { id: '59', shortId: 'pchuang', tableNumber: '12' },
    { id: '60', shortId: 'sandypan', tableNumber: '12' },
    { id: '61', shortId: 'iveshuang', tableNumber: '12' },
    { id: '62', shortId: 'tomhsieh', tableNumber: '12' },
    { id: '63', shortId: 'lewislau', tableNumber: '12' },
    { id: '64', shortId: 'clark45', tableNumber: '12' },
    { id: '65', shortId: 'kapean', tableNumber: '12' },
    { id: '66', shortId: 'hermit', tableNumber: '12' },
    { id: '67', shortId: 'peifeng', tableNumber: '16' },
    { id: '68', shortId: 'salleyl', tableNumber: '16' },
    { id: '69', shortId: 'manchi', tableNumber: '16' },
    { id: '70', shortId: 'ghsu01', tableNumber: '16' },
    { id: '71', shortId: 'vikii', tableNumber: '16' },
    { id: '72', shortId: 'wanchuan', tableNumber: '16' },
    { id: '73', shortId: 'dyang02', tableNumber: '16' },
    { id: '74', shortId: 'kkp', tableNumber: '16' },
    { id: '75', shortId: 'remyyu', tableNumber: '16' },
    { id: '76', shortId: 'samuri', tableNumber: '16' },
    { id: '77', shortId: 'susanl', tableNumber: '16' },
    { id: '78', shortId: 'hminyi', tableNumber: '17' },
    { id: '79', shortId: 'yyeh01', tableNumber: '17' },
    { id: '80', shortId: 'dodobeta', tableNumber: '17' },
    { id: '81', shortId: 'kaiyenkh', tableNumber: '17' },
    { id: '82', shortId: 'linshuyu', tableNumber: '17' },
    { id: '83', shortId: 'mlin03', tableNumber: '17' },
    { id: '84', shortId: 'afliang', tableNumber: '17' },
    { id: '85', shortId: 'mchen01', tableNumber: '17' },
    { id: '86', shortId: 'hhuang01', tableNumber: '17' },
    { id: '87', shortId: 'leiffu', tableNumber: '17' },
    { id: '88', shortId: 'chsieh06', tableNumber: '23' },
    { id: '89', shortId: 'chsieh07', tableNumber: '23' },
    { id: '90', shortId: 'uding01', tableNumber: '23' },
    { id: '91', shortId: 'ksu01', tableNumber: '23' },
    { id: '92', shortId: 'achang04', tableNumber: '21' },
    { id: '93', shortId: 'yumeih', tableNumber: '21' },
    { id: '94', shortId: 'betton', tableNumber: '21' },
    { id: '95', shortId: 'cindyhsu', tableNumber: '21' },
    { id: '96', shortId: 'twen01', tableNumber: '21' },
    { id: '97', shortId: 'kuojerfu', tableNumber: '21' },
    { id: '98', shortId: 'ylu11', tableNumber: '21' },
    { id: '99', shortId: 'yangcm', tableNumber: '21' },
    { id: '100', shortId: 'lchi', tableNumber: '21' },
    { id: '101', shortId: 'nancyhsu', tableNumber: '21' },
    { id: '102', shortId: 'ho', tableNumber: '22' },
    { id: '103', shortId: 'ochang', tableNumber: '22' },
    { id: '104', shortId: 'Peihsuanw', tableNumber: '22' },
    { id: '105', shortId: 'tzuchiw', tableNumber: '22' },
    { id: '106', shortId: 'weizhenh', tableNumber: '22' },
    { id: '107', shortId: 'felixcat', tableNumber: '22' },
    { id: '108', shortId: 'Clin14', tableNumber: '22' },
    { id: '109', shortId: 'areiclee', tableNumber: '22' },
    { id: '110', shortId: 'anapple lo', tableNumber: '22' },
    { id: '111', shortId: 'winona', tableNumber: '22' },
    { id: '112', shortId: 'yishian', tableNumber: '28' },
    { id: '113', shortId: 'annehyu', tableNumber: '28' },
    { id: '114', shortId: 'rchen03', tableNumber: '28' },
    { id: '115', shortId: 'cycheng', tableNumber: '28' },
    { id: '116', shortId: 'pcsung', tableNumber: '28' },
    { id: '117', shortId: 'twong01', tableNumber: '28' },
    { id: '118', shortId: 'chary', tableNumber: '28' },
    { id: '119', shortId: 'cwang05', tableNumber: '28' },
    { id: '120', shortId: 'cchen10', tableNumber: '28' },
    { id: '121', shortId: 'paulcp', tableNumber: '28' },
    { id: '122', shortId: 'kovenliao', tableNumber: '29' },
    { id: '123', shortId: 'ltsai', tableNumber: '29' },
    { id: '124', shortId: 'yhsieh01', tableNumber: '29' },
    { id: '125', shortId: 'mli05', tableNumber: '29' },
    { id: '126', shortId: 'ali04', tableNumber: '29' },
    { id: '127', shortId: 'ysun01', tableNumber: '29' },
    { id: '128', shortId: 'kyang02', tableNumber: '29' },
    { id: '129', shortId: 'ylu08', tableNumber: '29' },
    { id: '130', shortId: 'ychen33', tableNumber: '29' },
    { id: '131', shortId: 'gchang', tableNumber: '29' },
    { id: '132', shortId: 'daly', tableNumber: '37' },
    { id: '133', shortId: 'dho01', tableNumber: '37' },
    { id: '134', shortId: 'ychen06', tableNumber: '37' },
    { id: '135', shortId: 'ichuang', tableNumber: '37' },
    { id: '136', shortId: 'wchiu04', tableNumber: '37' },
    { id: '137', shortId: 'ptai', tableNumber: '37' },
    { id: '138', shortId: 'swang03', tableNumber: '37' },
    { id: '139', shortId: 'oualex', tableNumber: '37' },
    { id: '140', shortId: 'timlee', tableNumber: '37' },
    { id: '141', shortId: 'dhsieh02', tableNumber: '37' },
    { id: '142', shortId: 'wcshao', tableNumber: '38' },
    { id: '143', shortId: 'kaneshih', tableNumber: '38' },
    { id: '144', shortId: 'mltsai', tableNumber: '38' },
    { id: '145', shortId: 'dsu03', tableNumber: '38' },
    { id: '146', shortId: 'tcheong', tableNumber: '38' },
    { id: '147', shortId: 'cchang06', tableNumber: '38' },
    { id: '148', shortId: 'plin02', tableNumber: '38' },
    { id: '149', shortId: 'wpeng02', tableNumber: '38' },
    { id: '150', shortId: 'tkuo', tableNumber: '38' },
    { id: '151', shortId: 'lxchen', tableNumber: '38' },
    { id: '152', shortId: 'jetang', tableNumber: '45' },
    { id: '153', shortId: 'ychang01', tableNumber: '45' },
    { id: '154', shortId: 'jimho', tableNumber: '45' },
    { id: '155', shortId: 'nitachu', tableNumber: '45' },
    { id: '156', shortId: 'zxliao', tableNumber: '45' },
    { id: '157', shortId: 'cting02', tableNumber: '45' },
    { id: '158', shortId: 'peiyun', tableNumber: '45' },
    { id: '159', shortId: 'cwan01', tableNumber: '45' },
    { id: '160', shortId: 'glu01', tableNumber: '45' },
    { id: '161', shortId: 'rhsu02', tableNumber: '45' },
    { id: '162', shortId: 'puritys', tableNumber: '46' },
    { id: '163', shortId: 'lfu', tableNumber: '46' },
    { id: '164', shortId: 'schen28', tableNumber: '46' },
    { id: '165', shortId: 'jli07', tableNumber: '46' },
    { id: '166', shortId: 'plasma', tableNumber: '46' },
    { id: '167', shortId: 'yhuang15', tableNumber: '46' },
    { id: '168', shortId: 'ufohead', tableNumber: '46' },
    { id: '169', shortId: 'gwu', tableNumber: '46' },
    { id: '170', shortId: 'zhu', tableNumber: '46' },
    { id: '171', shortId: 'esun', tableNumber: '46' },
    { id: '172', shortId: 'carriec', tableNumber: '6' },
    { id: '173', shortId: 'natachac', tableNumber: '6' },
    { id: '174', shortId: 'chenvan', tableNumber: '6' },
    { id: '175', shortId: 'peian', tableNumber: '6' },
    { id: '176', shortId: 'viviwang', tableNumber: '6' },
    { id: '177', shortId: 'kuanwen', tableNumber: '6' },
    { id: '178', shortId: 'winniepan', tableNumber: '6' },
    { id: '179', shortId: 'seanchiang', tableNumber: '6' },
    { id: '180', shortId: 'bwchou', tableNumber: '6' },
    { id: '181', shortId: 'jc_tw', tableNumber: '6' },
    { id: '182', shortId: 'liukevin', tableNumber: '7' },
    { id: '183', shortId: 'henry228', tableNumber: '7' },
    { id: '184', shortId: 'joan', tableNumber: '7' },
    { id: '185', shortId: 'avis0001', tableNumber: '7' },
    { id: '186', shortId: 'cwendy', tableNumber: '7' },
    { id: '187', shortId: 'helencct', tableNumber: '7' },
    { id: '188', shortId: 'adaliou', tableNumber: '7' },
    { id: '189', shortId: 'tsyuki', tableNumber: '7' },
    { id: '190', shortId: 'lbetty', tableNumber: '7' },
    { id: '191', shortId: 'toncin', tableNumber: '7' },
    { id: '192', shortId: 'peilinoy', tableNumber: '8' },
    { id: '193', shortId: 'acertu', tableNumber: '8' },
    { id: '194', shortId: 'chatmere', tableNumber: '8' },
    { id: '195', shortId: 'asabrina', tableNumber: '8' },
    { id: '196', shortId: 'hosaile', tableNumber: '8' },
    { id: '197', shortId: 'joegao', tableNumber: '8' },
    { id: '198', shortId: 'kuochen', tableNumber: '8' },
    { id: '199', shortId: 'vivian71', tableNumber: '8' },
    { id: '200', shortId: 'jackiewu', tableNumber: '8' },
    { id: '201', shortId: 'lilylily', tableNumber: '8' },
    { id: '202', shortId: 'juchun', tableNumber: '13' },
    { id: '203', shortId: 'abellach', tableNumber: '13' },
    { id: '204', shortId: 'debbie1215', tableNumber: '13' },
    { id: '205', shortId: 'mickeylo', tableNumber: '13' },
    { id: '206', shortId: 'paul0310', tableNumber: '13' },
    { id: '207', shortId: 'stung', tableNumber: '13' },
    { id: '208', shortId: 'cherryfu', tableNumber: '13' },
    { id: '209', shortId: 'kangta', tableNumber: '13' },
    { id: '210', shortId: 'yoyowan', tableNumber: '13' },
    { id: '211', shortId: 'cmyiu', tableNumber: '13' },
    { id: '212', shortId: 'blackyan', tableNumber: '14' },
    { id: '213', shortId: 'vittyabc', tableNumber: '14' },
    { id: '214', shortId: 'rubytsen', tableNumber: '14' },
    { id: '215', shortId: 'mikiwu', tableNumber: '14' },
    { id: '216', shortId: 'peachwu', tableNumber: '14' },
    { id: '217', shortId: 'lynnchiu', tableNumber: '14' },
    { id: '218', shortId: 'allylin', tableNumber: '14' },
    { id: '219', shortId: 'jchan02', tableNumber: '14' },
    { id: '220', shortId: 'bli01', tableNumber: '14' },
    { id: '221', shortId: 'eding', tableNumber: '14' },
    { id: '222', shortId: 'michic', tableNumber: '20' },
    { id: '223', shortId: 'ellenlu', tableNumber: '20' },
    { id: '224', shortId: 'amandayw', tableNumber: '20' },
    { id: '225', shortId: 'klu03', tableNumber: '20' },
    { id: '226', shortId: 'jimmylo', tableNumber: '20' },
    { id: '227', shortId: 'ccchang', tableNumber: '20' },
    { id: '228', shortId: 'andyyeh', tableNumber: '20' },
    { id: '229', shortId: 'mhsu07', tableNumber: '20' },
    { id: '230', shortId: 'schen22', tableNumber: '20' },
    { id: '231', shortId: 'hli09', tableNumber: '26' },
    { id: '232', shortId: 'llo', tableNumber: '26' },
    { id: '233', shortId: 'iou', tableNumber: '26' },
    { id: '234', shortId: 'ylin17', tableNumber: '26' },
    { id: '235', shortId: 'wchen15', tableNumber: '26' },
    { id: '236', shortId: 'rtang01', tableNumber: '26' },
    { id: '237', shortId: 'llin07', tableNumber: '26' },
    { id: '238', shortId: 'cyu06', tableNumber: '26' },
    { id: '239', shortId: 'hluo', tableNumber: '26' },
    { id: '240', shortId: 'jyao02', tableNumber: '26' },
    { id: '241', shortId: 'sghost', tableNumber: '31' },
    { id: '242', shortId: 'bass', tableNumber: '31' },
    { id: '243', shortId: 'yukang', tableNumber: '32' },
    { id: '244', shortId: 'cli01', tableNumber: '32' },
    { id: '245', shortId: 'hsun01', tableNumber: '32' },
    { id: '246', shortId: 'jtien', tableNumber: '32' },
    { id: '247', shortId: 'ptran01', tableNumber: '32' },
    { id: '248', shortId: 'cchen21', tableNumber: '32' },
    { id: '249', shortId: 'ychen36', tableNumber: '32' },
    { id: '250', shortId: 'pkuo01', tableNumber: '32' },
    { id: '251', shortId: 'rwei', tableNumber: '32' },
    { id: '252', shortId: 'ghuang', tableNumber: '32' },
    { id: '253', shortId: 'tyeh01', tableNumber: '39' },
    { id: '254', shortId: 'ehou', tableNumber: '39' },
    { id: '255', shortId: 'hcheng02', tableNumber: '39' },
    { id: '256', shortId: 'dhung', tableNumber: '39' },
    { id: '257', shortId: 'syang07', tableNumber: '39' },
    { id: '258', shortId: 'lfang01', tableNumber: '39' },
    { id: '259', shortId: 'ywu07', tableNumber: '39' },
    { id: '260', shortId: 'ywang29', tableNumber: '39' },
    { id: '261', shortId: 'kuanyu', tableNumber: '39' },
    { id: '262', shortId: 'brook', tableNumber: '39' },
    { id: '263', shortId: 'gracelin', tableNumber: '40' },
    { id: '264', shortId: 'timliao', tableNumber: '40' },
    { id: '265', shortId: 'cwang04', tableNumber: '40' },
    { id: '266', shortId: 'achen09', tableNumber: '40' },
    { id: '267', shortId: 'cha0729', tableNumber: '40' },
    { id: '268', shortId: 'thuang04', tableNumber: '40' },
    { id: '269', shortId: 'dliu01', tableNumber: '40' },
    { id: '270', shortId: 'ycchien', tableNumber: '40' },
    { id: '271', shortId: 'jjy', tableNumber: '40' },
    { id: '272', shortId: 'jlin14', tableNumber: '40' },
    { id: '273', shortId: 'ehsu02', tableNumber: '47' },
    { id: '274', shortId: 'bfan01', tableNumber: '47' },
    { id: '275', shortId: 'webblin', tableNumber: '47' },
    { id: '276', shortId: 'gtso', tableNumber: '47' },
    { id: '277', shortId: 'nkuo', tableNumber: '47' },
    { id: '278', shortId: 'zoehuang', tableNumber: '47' },
    { id: '279', shortId: 'shenmengyan', tableNumber: '47' },
    { id: '280', shortId: 'jameschen', tableNumber: '47' },
    { id: '281', shortId: 'simon32840', tableNumber: '47' },
    { id: '282', shortId: 'thsu03', tableNumber: '47' },
    { id: '283', shortId: 'caroly31', tableNumber: '48' },
    { id: '284', shortId: 'pconnieq', tableNumber: '48' },
    { id: '285', shortId: 'weiningy', tableNumber: '48' },
    { id: '286', shortId: 'chihanm', tableNumber: '48' },
    { id: '287', shortId: 'ichin', tableNumber: '48' },
    { id: '288', shortId: 'yychris', tableNumber: '48' },
    { id: '289', shortId: 'yunju', tableNumber: '48' },
    { id: '290', shortId: 'ruruchen', tableNumber: '48' },
    { id: '291', shortId: 'alin07', tableNumber: '48' },
    { id: '292', shortId: 'rita87069', tableNumber: '48' },
    { id: '293', shortId: 'crystal0531', tableNumber: '53' },
    { id: '294', shortId: 'tchiaping', tableNumber: '53' },
    { id: '295', shortId: 'alin01', tableNumber: '53' },
    { id: '296', shortId: 'dailic', tableNumber: '53' },
    { id: '297', shortId: 'innelai', tableNumber: '53' },
    { id: '298', shortId: 'pinhsueh', tableNumber: '53' },
    { id: '299', shortId: 'tsengyil', tableNumber: '53' },
    { id: '300', shortId: 'joyce60126', tableNumber: '53' },
    { id: '301', shortId: 'yupi520', tableNumber: '53' },
    { id: '302', shortId: 'fangrul', tableNumber: '53' },
    { id: '303', shortId: 'nchung01', tableNumber: '54' },
    { id: '304', shortId: 'chen0506', tableNumber: '54' },
    { id: '305', shortId: 'kissas', tableNumber: '54' },
    { id: '306', shortId: 'chihyingw', tableNumber: '54' },
    { id: '307', shortId: 'klin04', tableNumber: '54' },
    { id: '308', shortId: 'meil', tableNumber: '54' },
    { id: '309', shortId: 'winniey', tableNumber: '54' },
    { id: '310', shortId: 'bwu03', tableNumber: '54' },
    { id: '311', shortId: 'wanyi531', tableNumber: '54' },
    { id: '312', shortId: 'ryanpeng', tableNumber: '54' },
    { id: '313', shortId: 'rchang02', tableNumber: '55' },
    { id: '314', shortId: 'ilu', tableNumber: '55' },
    { id: '315', shortId: 'Yawenla', tableNumber: '55' },
    { id: '316', shortId: 'pattyl', tableNumber: '55' },
    { id: '317', shortId: 'yliao', tableNumber: '55' },
    { id: '318', shortId: 'fciou', tableNumber: '55' },
    { id: '319', shortId: 'lderrick', tableNumber: '55' },
    { id: '320', shortId: 'leochen', tableNumber: '55' },
    { id: '321', shortId: 'tinyih', tableNumber: '55' },
    { id: '322', shortId: 'scheng02', tableNumber: '55' },
    { id: '323', shortId: 'ipenny', tableNumber: '56' },
    { id: '324', shortId: 'mayaya', tableNumber: '56' },
    { id: '325', shortId: 'amymanna', tableNumber: '56' },
    { id: '326', shortId: 'hlinouob', tableNumber: '56' },
    { id: '327', shortId: 'shichung', tableNumber: '56' },
    { id: '328', shortId: 'clee05', tableNumber: '56' },
    { id: '329', shortId: 'erickuo', tableNumber: '56' },
    { id: '330', shortId: 'lliu01', tableNumber: '56' },
    { id: '331', shortId: 'hankting', tableNumber: '56' },
    { id: '332', shortId: 'multani', tableNumber: '56' },
    { id: '333', shortId: 'mikeliu', tableNumber: '61' },
    { id: '334', shortId: 'cchang08', tableNumber: '61' },
    { id: '335', shortId: 'jlee10', tableNumber: '61' },
    { id: '336', shortId: 'mtsai07', tableNumber: '61' },
    { id: '337', shortId: 'weihsuehl', tableNumber: '61' },
    { id: '338', shortId: 'ylee02', tableNumber: '61' },
    { id: '339', shortId: 'dereklin', tableNumber: '61' },
    { id: '340', shortId: 'larryliang', tableNumber: '61' },
    { id: '341', shortId: 'cyme', tableNumber: '61' },
    { id: '342', shortId: 'sonyshhc', tableNumber: '61' },
    { id: '343', shortId: 'chuang07', tableNumber: '62' },
    { id: '344', shortId: 'ctchou', tableNumber: '62' },
    { id: '345', shortId: 'xcheng', tableNumber: '62' },
    { id: '346', shortId: 'kchen05', tableNumber: '62' },
    { id: '347', shortId: 'mliu01', tableNumber: '62' },
    { id: '348', shortId: 'nchiang', tableNumber: '62' },
    { id: '349', shortId: 'pwang02', tableNumber: '62' },
    { id: '350', shortId: 'wchen14', tableNumber: '62' },
    { id: '351', shortId: 'cytms', tableNumber: '62' },
    { id: '352', shortId: 'tcliou', tableNumber: '62' },
    { id: '353', shortId: 'achen08', tableNumber: '63' },
    { id: '354', shortId: 'cchang09', tableNumber: '63' },
    { id: '355', shortId: 'csu01', tableNumber: '63' },
    { id: '356', shortId: 'wylin', tableNumber: '63' },
    { id: '357', shortId: 'iansu', tableNumber: '63' },
    { id: '358', shortId: 'iip', tableNumber: '63' },
    { id: '359', shortId: 'jhsu01', tableNumber: '63' },
    { id: '360', shortId: 'salagado', tableNumber: '63' },
    { id: '361', shortId: 'bku', tableNumber: '63' },
    { id: '362', shortId: 'pliu01', tableNumber: '63' },
    { id: '363', shortId: 'titanwu', tableNumber: '64' },
    { id: '364', shortId: 'elliet', tableNumber: '64' },
    { id: '365', shortId: 'clin13', tableNumber: '64' },
    { id: '366', shortId: 'daisylin', tableNumber: '64' },
    { id: '367', shortId: 'hvan', tableNumber: '64' },
    { id: '368', shortId: 'jannewu', tableNumber: '64' },
    { id: '369', shortId: 'choutung', tableNumber: '64' },
    { id: '370', shortId: 'tinayswu', tableNumber: '64' },
    { id: '371', shortId: 'miyabi0630', tableNumber: '64' },
    { id: '372', shortId: 'iusanlie', tableNumber: '64' },
    { id: '373', shortId: 'sanderw', tableNumber: '69' },
    { id: '374', shortId: 'yunan', tableNumber: '69' },
    { id: '375', shortId: 'kevinhsu', tableNumber: '69' },
    { id: '376', shortId: 'alberth', tableNumber: '69' },
    { id: '377', shortId: 'leonkulo', tableNumber: '69' },
    { id: '378', shortId: 'lliu04', tableNumber: '69' },
    { id: '379', shortId: 'jackc', tableNumber: '69' },
    { id: '380', shortId: 'pcheng01', tableNumber: '69' },
    { id: '381', shortId: 'foxer', tableNumber: '69' },
    { id: '382', shortId: 'emendel', tableNumber: '69' },
    { id: '383', shortId: 'ada', tableNumber: '70' },
    { id: '384', shortId: 'hsuanling', tableNumber: '70' },
    { id: '385', shortId: 'katykuo', tableNumber: '70' },
    { id: '386', shortId: 'hsiuchen', tableNumber: '70' },
    { id: '387', shortId: 'inting', tableNumber: '70' },
    { id: '388', shortId: 'ericyh', tableNumber: '70' },
    { id: '389', shortId: 'shenghua', tableNumber: '70' },
    { id: '390', shortId: 'cookies', tableNumber: '70' },
    { id: '391', shortId: 'skuo02', tableNumber: '70' },
    { id: '392', shortId: 'suantost', tableNumber: '70' },
    { id: '393', shortId: 'slin02', tableNumber: '70' },
  ]);
  const [searchQuery, setSearchQuery] = useState('');

  // 精確搜尋短ID
  const filteredSeats = seats.filter((seat) => {
    if (!searchQuery.trim()) return false; // 沒有搜尋條件時不顯示任何結果
    const query = searchQuery.toLowerCase();
    return seat.shortId.toLowerCase() === query; // 完全符合才顯示
  });

  const handleSearch = (query: string) => {
    setSearchQuery(query);
  };

  const handleAddSeat = (newSeat: Omit<Seat, 'id'>) => {
    const seat: Seat = {
      ...newSeat,
      id: Date.now().toString(),
    };
    setSeats([...seats, seat]);
  };

  return (
    <div className="min-h-screen bg-gradient-to-br from-indigo-600 via-purple-600 to-pink-600 relative overflow-hidden">
      {/* 3D 背景裝飾 */}
      <div className="absolute inset-0 overflow-hidden pointer-events-none">
        <div className="absolute top-20 left-10 w-32 h-32 bg-yellow-400 rounded-full opacity-20 blur-3xl"></div>
        <div className="absolute bottom-20 right-10 w-40 h-40 bg-pink-400 rounded-full opacity-20 blur-3xl"></div>
        <div className="absolute top-1/2 left-1/2 w-64 h-64 bg-purple-400 rounded-full opacity-10 blur-3xl"></div>
      </div>
      
      <div className="container mx-auto px-4 py-12 max-w-4xl relative z-10" style={{ perspective: '1000px' }}>
        {/* Header */}
        <div className="text-center mb-12 transform hover:scale-105 transition-transform duration-300">
          <h1 className="text-white mb-3 drop-shadow-2xl" style={{ textShadow: '0 10px 30px rgba(0,0,0,0.3), 0 0 20px rgba(255,255,255,0.2)' }}>
            🍽️ 餐廳座位搜尋系統
          </h1>
          <p className="text-white/95 drop-shadow-lg">輸入短ID或桌號來搜尋座位資訊</p>
        </div>

        {/* Search Section */}
        <div 
          className="bg-gradient-to-br from-yellow-100 to-yellow-50 rounded-3xl p-8 mb-8 transform hover:translate-y-[-8px] transition-all duration-300"
          style={{ 
            boxShadow: '0 20px 60px rgba(0,0,0,0.3), 0 0 0 1px rgba(255,255,255,0.1), inset 0 1px 0 rgba(255,255,255,0.6)',
            transform: 'rotateX(2deg)'
          }}
        >
          <SearchBar 
            onSearch={handleSearch}
          />
        </div>

        {/* Results Section */}
        <div 
          className="bg-gradient-to-br from-blue-100 to-cyan-50 rounded-3xl p-8 transform hover:translate-y-[-8px] transition-all duration-300"
          style={{ 
            boxShadow: '0 20px 60px rgba(0,0,0,0.3), 0 0 0 1px rgba(255,255,255,0.1), inset 0 1px 0 rgba(255,255,255,0.6)',
            transform: 'rotateX(2deg)'
          }}
        >
          <div className="flex items-center justify-between mb-6">
            <h2 className="text-pink-700 drop-shadow-md" style={{ textShadow: '2px 2px 4px rgba(0,0,0,0.1)' }}>
              🔍 搜尋結果
            </h2>
            <span 
              className="text-purple-700 bg-white px-6 py-2 rounded-full shadow-lg"
              style={{ boxShadow: '0 4px 15px rgba(0,0,0,0.2), inset 0 -2px 5px rgba(0,0,0,0.1)' }}
            >
              共 {filteredSeats.length} 筆結果
            </span>
          </div>
          <SeatList seats={filteredSeats} searchQuery={searchQuery} />
        </div>
      </div>
    </div>
  );
}